{% set version = "2.0.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-googleauthr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/googleAuthR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/googleAuthR/googleAuthR_{{ version }}.tar.gz
  sha256: 9b19a63bc250151674f20b27389baa95c10cc62dc7c3c0ff12a8d684bdb8a14b

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-assertthat >=0.2.0
    - r-cli >=2.0.2
    - r-digest
    - r-gargle >=0.4.0
    - r-httr >=1.4.0
    - r-jsonlite >=1.6
    - r-memoise >=1.1.0
    - r-rlang
  run:
    - r-base
    - r-assertthat >=0.2.0
    - r-cli >=2.0.2
    - r-digest
    - r-gargle >=0.4.0
    - r-httr >=1.4.0
    - r-jsonlite >=1.6
    - r-memoise >=1.1.0
    - r-rlang

test:
  commands:
    - $R -e "library('googleAuthR')"           # [not win]
    - "\"%R%\" -e \"library('googleAuthR')\""  # [win]

about:
  home: http://code.markedmondson.me/googleAuthR/
  license: MIT
  summary: Create R functions that interact with OAuth2 Google APIs  <https://developers.google.com/apis-explorer/> easily, with auto-refresh and Shiny compatibility.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: googleAuthR
# Type: Package
# Version: 1.1.1
# Title: Authenticate and Create Google APIs
# Description: Create R functions that interact with OAuth2 Google APIs  <https://developers.google.com/apis-explorer/> easily, with auto-refresh and Shiny compatibility.
# Authors@R: c(person("Mark", "Edmondson",email = "m@sunholo.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-8434-3881")), person("Jennifer", "Bryan",email="jenny@stat.ubc.ca", role = "ctb"), person("Johann", "deBoer", email="johanndeboer@gmail.com", role = "ctb"), person("Neal", "Richardson", email="neal.p.richardson@gmail.com", role = "ctb"), person("David","Kulp", email="dkulp@cs.umass.edu", role = "ctb"), person("Joe","Cheng", email = "joe@rstudio.com", role = "ctb"))
# URL: http://code.markedmondson.me/googleAuthR/
# BugReports: https://github.com/MarkEdmondson1234/googleAuthR/issues
# Depends: R (>= 3.3.0)
# Imports: assertthat (>= 0.2.0), digest, gargle (>= 0.3.1), httr (>= 1.4.0), jsonlite (>= 1.6), memoise (>= 1.1.0), rlang, utils
# Suggests: bigQueryR, covr, devtools (>= 1.12.0), formatR (>= 1.4), googleAnalyticsR, knitr, miniUI (>= 0.1.1), rmarkdown, roxygen2 (>= 5.0.0), shiny (>= 0.13.2), testthat, usethis (>= 1.5.1)
# License: MIT + file LICENSE
# LazyData: true
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-09-08 21:54:49 UTC; mark
# Author: Mark Edmondson [aut, cre] (<https://orcid.org/0000-0002-8434-3881>), Jennifer Bryan [ctb], Johann deBoer [ctb], Neal Richardson [ctb], David Kulp [ctb], Joe Cheng [ctb]
# Maintainer: Mark Edmondson <m@sunholo.com>
# Repository: CRAN
# Date/Publication: 2019-09-09 08:00:02 UTC
