appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: TIuUwfZTIJMgeiL9fjbBoeWXOjmm3JwmXS6NGaGRJ7TP0qs7Mbt3HDAM9uc6ja2wa93Z8w6YFF8U2RB+or40hT6WqoVAr0ydEnlPuc5neWVjdGnkrSEmHLfCpwLL3PxPtnOLWrGtZUV9YpMmnd3LdSdiUhWBoSKiwtUn4eHdRVIEMaVegyjrFhzCDUbNOKnbdXUNa7zmHtRcmT+xXHnmlJsIgPWJRAVI4xziswO1jI4k+gM+Enq2qNJLRMEiC3L4zcAvLVUf339LKDcBxY523VzVKL58l0mPDQWi8oYaIh4UV1k7BbKsD/0rtDXJzZK1UhIQVHTYNB40NNVY0j0ahOUk7JFMn0e2H1qPKB6UYXxAxls+oZIX0/Fa2dKytYSdU4PmMb3HBvhTY2Sa4JsFpuF0u2AhWCJQwRM3rC2GO6BHsJKLN8CbT4WahTud4dq94qcwIMRZUwRGqPOShRFanl1fMQFd+ELKlEMla6D3IP8FlQpll4U+erHJnRLe9qGqCsWd1MxF0521W1qdPM57W7lSnWKrp29t5sSRSEhQHxCo0qqvbD9GxdLY8UrkLtJQvm2D/FikucP7+AlbIi1uMGLb9pHigL+sBjlNBmTokv6UdABTqihvdFLMAksz184FQf2gM7dcw+T9oQIiUwfxCqYpewd7R9QZUcOjeMONpVA=}
